
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yunuspektas
 */
public class StokUygulamasi extends javax.swing.JFrame {

    /**
     * Creates new form StokUygulamasi
     */
    public StokUygulamasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_urun_ismi = new javax.swing.JTextField();
        cb_kategori = new javax.swing.JComboBox<>();
        tf_fiyat = new javax.swing.JTextField();
        mesaj_yazisi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        urun_tablosu = new javax.swing.JTable();
        ekle_butonu = new javax.swing.JButton();
        guncelle_butonu = new javax.swing.JButton();
        sil_butonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ürün İsmi:");

        jLabel2.setText("Kategori:");

        jLabel3.setText("Fiyat:");

        cb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kültür Sanat", "Yemek", "Elektronik" }));

        mesaj_yazisi.setForeground(new java.awt.Color(255, 0, 51));

        urun_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün İsmi", "Kategori", "Fiyat"
            }
        ));
        urun_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urun_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(urun_tablosu);

        ekle_butonu.setText("Ürün Ekle");
        ekle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle_butonuActionPerformed(evt);
            }
        });

        guncelle_butonu.setText("Ürün Güncelle");
        guncelle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle_butonuActionPerformed(evt);
            }
        });

        sil_butonu.setText("Ürün Sil");
        sil_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_butonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_urun_ismi, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(38, 38, 38))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_kategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ekle_butonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guncelle_butonu, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(sil_butonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_urun_ismi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekle_butonu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guncelle_butonu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sil_butonu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle_butonuActionPerformed
        mesaj_yazisi.setText(""); // her seferinde güncellemek için mesaj yazısını temizledik
        
        DefaultTableModel model = (DefaultTableModel) urun_tablosu.getModel();
        //JTable işlem yapmak için DefaultTableModel ile referans oluşturup eşitliyoruz. tabloyu getModel metoduyla alıyoruz
        //(DefaultTableModel) modelimizi bu şekilde tür dönüşümü yapmalıyız
        
        if (tf_urun_ismi.getText().trim().equals("")) {
            //trim metodu başındaki sondaki boşlukları silmek için kullanır
            mesaj_yazisi.setText("Ürün ismi boş bırakılamaz.");
         }
        else{
            Object[] eklenecek = {tf_urun_ismi.getText(),cb_kategori.getSelectedItem().toString(),tf_fiyat.getText() };
            // bu şekilde obje arreyi oluşturduk , obje olmasının sebebi defaulttablemodel ile ilegili
            //tabloya defaulttablemodel kullanarak ekleyeceğimiz için javayla alakalı object array istiyor
                    //toString ile string olarak döndük
                    
                    model.addRow(eklenecek);
                    //object arrayle ekliyor , referans ismi ve addRow metodu tabloya değer ekler. row sıra demek. sırayla ekle gibi 
                    
        }            
        
        
        
    }//GEN-LAST:event_ekle_butonuActionPerformed

    private void guncelle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle_butonuActionPerformed
      mesaj_yazisi.setText("");
      
      DefaultTableModel model = (DefaultTableModel)  urun_tablosu.getModel();
      
      int secili_row = urun_tablosu.getSelectedRow();
      //JTablo da .getSelectedRow(); metodu hangi rowa(sıraya) tıklanmışsa o row un değerini bize sıra değeerini söyleyecek. indexini
      //eğer hiç bir yere tıklanmamışsa getSelectedRow -1 değerini döner
      
      if(secili_row == -1){
          // seçili row'un -1 değeri dönmesinin iki sebebi var eğer tablomuz boşsa -1 döner
          // yada tabloda hiç bir rowu seçmediysek -1 değeri döner
          if(urun_tablosu.getRowCount() == 0){
              //JTable deki getRowCount metodu kaç tane satır varsa o sayıyı döner
              // eğer hiçbir satırımız yoksa getRowCount sıfır döner
              
              mesaj_yazisi.setText("Ürün tablosu şu anda boş.");
              
          }
          else{
              mesaj_yazisi.setText("Lütfen güncellenecek bir ürün seçiniz. ");
          }
          
      }
      else{
          model.setValueAt(tf_urun_ismi.getText(), secili_row, 0);
          model.setValueAt(cb_kategori.getSelectedItem().toString(), secili_row, 1);
         model.setValueAt(tf_fiyat.getText() ,secili_row, 2);
         // aynı yerler tekrardan güncellenmez
          mesaj_yazisi.setText("Ürün başarıyla güncellendi.");

  
//column sütun demek
          //DefaultTableModel deki setValueAt metoduyla güncelleme yaparız. bize hangi satırın hangi sütunu günvelenecek diye soruyor
          // ne ismini güncelleyeceğimiz sütun satır değerindeki ismi objeyide  yazmamız gerekiyor
          //JTable de güncellemeyi DefaultTableModel deki setValueAt metoduyla yapabiliriz
      }
      
      
    }//GEN-LAST:event_guncelle_butonuActionPerformed

    private void urun_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urun_tablosuMouseClicked
       DefaultTableModel model = (DefaultTableModel) urun_tablosu.getModel();
       //DefaultTableModeli JTablomuzdan türetmemiz gerekiyo 
       
       int secili_row = urun_tablosu.getSelectedRow();
       
       tf_urun_ismi.setText(model.getValueAt(secili_row, 0).toString());
       cb_kategori.setSelectedItem(model.getValueAt(secili_row, 1).toString());//combobox da setSelectedItem o an ki değeri değiştirir
       tf_fiyat.setText(model.getValueAt(secili_row, 2).toString());
       //DefaultTableModel deki getValueAt object türünden döndüğü için stringe çevirmemiz gerekiyo
       //toString metoduyla objemizi stringe çevirebiliriz
       //burada JTable de tıkladığımız yerin değer girdipimiz yere eşit olması için yazdık
       //bunuda modeldeki.getValueAT metoduyla sağladık ve seçtiğimiz rowu almak içinse
       //yine DefaultTableModel deki getSelectedRow(); metoduyla yaptık
       
       
       
    }//GEN-LAST:event_urun_tablosuMouseClicked

    private void sil_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_butonuActionPerformed
       DefaultTableModel model = (DefaultTableModel) urun_tablosu.getModel();
       mesaj_yazisi.setText("");
       int secili_row = urun_tablosu.getSelectedRow();
       // eğer tablom boşsa getSelectedRow -1 döner
       // eğer hiçö bir şey seçmemişsem getSelectedRow -1 döner
       // rowlar array gibi 0 dan başlar
       
        if (secili_row == -1) {
            if(urun_tablosu.getRowCount() == 0){//DefaultTableModel deki getRowCount  tablodaki değer sayısını verir. değer yoksa boşsa sıfır verecek
                //count saymak
                mesaj_yazisi.setText("Ürün tablosu şu anda boş.");
            }
            else{// rowum var ama seçmemişim
                mesaj_yazisi.setText("LÜtfen silenecek bir ürün seçiniz.");
            }
            
        }
        else{
            model.removeRow(secili_row);
            //DefaultTableModel deki removeRow sayesinde verdiğimiz row indexini siler. idsini verdik
            //getSelectedRow() ile aldığımız seçili rowu verdik ve sildik
            
            mesaj_yazisi.setText("Ürün başarıyla silindi.");
        }
    }//GEN-LAST:event_sil_butonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StokUygulamasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_kategori;
    private javax.swing.JButton ekle_butonu;
    private javax.swing.JButton guncelle_butonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JButton sil_butonu;
    private javax.swing.JTextField tf_fiyat;
    private javax.swing.JTextField tf_urun_ismi;
    private javax.swing.JTable urun_tablosu;
    // End of variables declaration//GEN-END:variables
}
